services:

    nginx-rtmp:
        image: tiangolo/nginx-rtmp
        container_name: nginx-rtmp
        ports:
            - "1935:1935"
            - "8080:8080"
        volumes:
            - ./volumes/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
            - ./volumes/nginx/hls:/tmp/hls
        networks:
            - nginx

networks:
    nginx:
